services:
  postgres:
    image: postgres:14-alpine
    container_name: codepush-postgres
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DATABASE: codepush
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: codepush-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: codepush
    command: /opt/bitnami/minio/bin/minio server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - ./minio-data:/data

volumes:
  postgres-data:
  minio-data:
