services:
  mysql:
    image: mysql:8.0
    container_name: codepush-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codepush
      MYSQL_USER: codepush
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/codepush-all-docker.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: docker.io/bitnami/minio:latest
    container_name: codepush-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: codepush
    command: /opt/bitnami/minio/bin/minio server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
  minio-data:
